project:
  type: website
  output-dir: docs

website:
  title: "Antonio Carlos Rodrigues"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with RStudio {{< iconify file-icons:rstudio >}} and Quarto [{{< iconify simple-icons:quarto >}}](https://quarto.org/)"
  navbar:
    right:
      - href: blog/index.qmd
      #- href: teaching/index.qmd
      #- href: publications.qmd
format:
  html:
    theme: [cosmo, styles.scss]
    include-in-header:
      - text: "<script src='https://code.iconify.design/2/2.0.0-rc2/iconify.min.js'></script>"


